#!/bin/bash
app=painter

# Retrieve arguments
domain=$1
path=$2
admin=$3
is_public=$4

# Save app settings
sudo yunohost app setting $app admin -v "$admin"
sudo yunohost app setting $app is_public -v "$is_public"

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

final_path=/var/www/$app
sudo mkdir -p $final_path
sudo apt-get install unzip
echo "Downloading Painter master version..."
mkdir ../tmp
sudo wget -O ../tmp/master.zip "https://github.com/estrolix/Painter/archive/master.zip"
echo "Deploying source files..."
unzip ../tmp/master.zip -d ../tmp/master
sudo cp -a ../tmp/master/Painter-master/* $final_path
sudo rm -r ../tmp/master
sudo chown -R www-data: $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# If app is public, add url to SSOWat conf as skipped_uris
if [ "$is_public" = "Yes" ];
then
  # unprotected_uris allows SSO credentials to be passed anyway.
  sudo yunohost app setting $app unprotected_uris -v "/"
fi

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf
